{% set version = "0.12" %}

package:
  name: opusfile
  version: {{ version }}

source:
  url: https://ftp.osuosl.org/pub/xiph/releases/opus/opusfile-{{ version }}.tar.gz
  sha256: 118d8601c12dd6a44f52423e68ca9083cc9f2bfe72da7a8c1acb22a80ae3550b
  patches:
    # https://github.com/conda/conda-build/issues/3165
    - 0001-Disable-GNU_SOURCE.patch

build:
  number: 1
  skip: true  # [win]
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/opusfile
    - {{ pin_subpackage("opusfile", max_pin="x.x") }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
    - pkgconfig
  host:
    - libopus
    - libogg
    - openssl
  run:
    - libopus
    - libogg
    - openssl

test:
  commands:
    - test -f ${PREFIX}/include/opus/opusfile.h
    - test -f ${PREFIX}/lib/libopusfile${SHLIB_EXT}

about:
  home: https://github.com/xiph/opusfile
  license: BSD-3-Clause
  license_file: COPYING
  summary: Stand-alone decoder library for .opus streams

extra:
  recipe-maintainers:
    - asafkahlon
